#!/usr/local/bin/perl -w
$grammar = $ARGV[0];
$sentences = $ARGV[1];

system("java -Xmx128m earley2.Earley $grammar $sentences");
system("perl prettyprint OUTPUT");
system("perl prettyprint OUTPUT > PRETTY_OUTPUT");
