#!/bin/sh

echo "Converting to DIMACS...."
perl convertToDIMACS.pl $1.cnf > $1.DIMACS
echo "Solving with zChaff...."
/usr/local/data/cs325/hw1/zChaff/zchaff $1.DIMACS > $1.solution
echo "Trimming...."
perl trimoutput.pl $1.solution > $1.trimmed
echo "Converting...."
perl convertBack.pl $1.trimmed $1.key > $1.output
