INSERT INTO GemTable VALUES('Chipped', 'Skull', 1, 'Steals 2% life, 1% Mana', 'Attacker Takes 4 Damage', 'Replenish Life +2, Regenerate Mana 8%');
INSERT INTO GemTable VALUES('Flawed', 'Skull', 5, 'Steals 2% life, 2% Mana', 'Attacker Takes 8 Damage', 'Replenish Life +3, Regenerate Mana 8%');
INSERT INTO GemTable VALUES('Normal', 'Skull', 12, 'Steals 3% life, 2% Mana', 'Attacker Takes 12 Damage', 'Replenish Life +3, Regenerate Mana 12%');
INSERT INTO GemTable VALUES('Flawless', 'Skull', 15, 'Steals 3% life, 3% Mana', 'Attacker Takes 16 Damage', 'Replenish Life +4, Regenerate Mana 12%');
INSERT INTO GemTable VALUES('Perfect', 'Skull', 18, 'Steals 4% life, 3% Mana', 'Attacker Takes 20 Damage', 'Replenish Life +5, Regenerate Mana 19%');
INSERT INTO GemTable VALUES('Chipped', 'Amethyst', 1, '+40 to Attack Rating', '+8 to Defense', '+3 to Strength');
INSERT INTO GemTable VALUES('Flawed', 'Amethyst', 5, '+60 to Attack Rating', '+12 to Defense', '+4 to Strength');
INSERT INTO GemTable VALUES('Normal', 'Amethyst', 12, '+80 to Attack Rating', '+18 to Defense', '+6 to Strength');
INSERT INTO GemTable VALUES('Flawless', 'Amethyst', 15, '+100 to Attack Rating', '+24 to Defense', '+8 to Strength');
INSERT INTO GemTable VALUES('Perfect', 'Amethyst', 18, '+150 to Attack Rating', '+30 to Defense', '+10 to Strength');
INSERT INTO GemTable VALUES('Chipped', 'Sapphire', 1, '1-3 Cold Damage - 1.0 sec Duration', '12% Resist Cold', '+10 Max Mana');
INSERT INTO GemTable VALUES('Flawed', 'Sapphire', 5, '3-5 Cold Damage - 1.4 sec Duration', '16% Resist Cold', '+17 Max Mana');
INSERT INTO GemTable VALUES('Normal', 'Sapphire', 12, '4-7 Cold Damage - 2.0 sec Duration', '22% Resist Cold', '+24 Max Mana');
INSERT INTO GemTable VALUES('Flawless', 'Sapphire', 15, '6-10 Cold Damage - 2.4 sec Duration', '28% Resist Cold', '+31 Max Mana');
INSERT INTO GemTable VALUES('Perfect', 'Sapphire', 18, '10-14 Cold Damage - 3.0 sec Duration', '40% Resist Cold', '+38 Max Mana');
INSERT INTO GemTable VALUES('Chipped', 'Emerald', 1, '+10 Poison Damage over 3 Seconds', '12% Resist Poison', '+3 to Dexterity');
INSERT INTO GemTable VALUES('Flawed', 'Emerald', 5, '+20 Poison Damage over 4 Seconds', '16% Resist Poison', '+4 to Dexterity');
INSERT INTO GemTable VALUES('Normal', 'Emerald', 12, '+40 Poison Damage over 5 Seconds', '22% Resist Poison', '+6 to Dexterity');
INSERT INTO GemTable VALUES('Flawless', 'Emerald', 15, '+60 Poison Damage over 6 Seconds', '28% Resist Poison', '+8 to Dexterity');
INSERT INTO GemTable VALUES('Perfect', 'Emerald', 18, '+100 Poison Damage over 7 Seconds', '40% Resist Poison', '+10 to Dexterity');
INSERT INTO GemTable VALUES('Chipped', 'Ruby', 1, '3-4 Fire Damage', '12% Resist Fire', '+10 to Life');
INSERT INTO GemTable VALUES('Flawed', 'Ruby', 5, '5-8 Fire Damage', '16% Resist Fire', '+17 to Life');
INSERT INTO GemTable VALUES('Normal', 'Ruby', 12, '8-12 Fire Damage', '22% Resist Fire', '+24 to Life');
INSERT INTO GemTable VALUES('Flawless', 'Ruby', 15, '10-16 Fire Damage', '28% Resist Fire', '+31 to Life');
INSERT INTO GemTable VALUES('Perfect', 'Ruby', 18, '15-20 Fire Damage', '40% Resist Fire', '+38 to Life');
INSERT INTO GemTable VALUES('Chipped', 'Diamond', 1, '+28% Damage vs. Undead', 'All Resistances +6%', '+20 to attack Rating');
INSERT INTO GemTable VALUES('Flawed', 'Diamond', 5, '+34% Damage vs. Undead', 'All Resistances +8%', '+40 to attack Rating');
INSERT INTO GemTable VALUES('Normal', 'Diamond', 12, '+44% Damage vs. Undead', 'All Resistances +11%', '+60 to attack Rating');
INSERT INTO GemTable VALUES('Flawless', 'Diamond', 15, '+54% Damage vs. Undead', 'All Resistances +14%', '+80 to attack Rating');
INSERT INTO GemTable VALUES('Perfect', 'Diamond', 18, '+68% Damage vs. Undead', 'All Resistances +19%', '+100 to attack Rating');
INSERT INTO GemTable VALUES('Chipped', 'Topaz', 1, '1-8 Lightning Damage', '12% Resist Lightning', '+9% Chance to Find Magic Items');
INSERT INTO GemTable VALUES('Flawed', 'Topaz', 5, '1-14 Lightning Damage', '16% Resist Lightning', '+13% Chance to Find Magic Items');
INSERT INTO GemTable VALUES('Normal', 'Topaz', 12, '1-22 Lightning Damage', '22% Resist Lightning', '+16% Chance to Find Magic Items');
INSERT INTO GemTable VALUES('Flawless', 'Topaz', 15, '1-30 Lightning Damage', '28% Resist Lightning', '+20% Chance to Find Magic Items');
INSERT INTO GemTable VALUES('Perfect', 'Topaz', 18, '1-40 Lightning Damage', '40% Resist Lightning', '+24% Chance to Find Magic Items');

INSERT INTO RuneTable VALUES('El', '+50 To Attack Rating, +1 Light Radius', '+15 Defense, +1 To Light Radius', '+15 Defense, +1 To Light Radius', 11);
INSERT INTO RuneTable VALUES('Eld', '+75% Damage To Undead, +50 Attack Rating Against Undead', '15% Slower Stamina Drain', '7% Increased Chance of Blocking', 11);
INSERT INTO RuneTable VALUES('Tir', '+2 To Mana After Each Kill', '+2 To Mana After Each Kill', '+2 To Mana After Each Kill', 13);
INSERT INTO RuneTable VALUES('Nef', 'Knockback', '+30 Defense vs. Missile', '+30 Defense vs. Missile', 13);
INSERT INTO RuneTable VALUES('Eth', '-25% To Target Defense', 'Regenerate Mana 15%', 'Regenerate Mana 15%', 15);
INSERT INTO RuneTable VALUES('Ith', '+9 To Maximum Damage', '15% Damage Taken Goes to Mana', '15% Damage Taken Goes to Mana', 15);
INSERT INTO RuneTable VALUES('Tal', '+75 Poison Damage Over 5 Seconds', 'Poison Resist 30%', 'Poison Resist 35%', 17);
INSERT INTO RuneTable VALUES('Ral', 'Adds 5-30 Fire Damage', 'Fire Resist 30%', 'Fire Resist 35%', 19);
INSERT INTO RuneTable VALUES('Ort', 'Adds 1-50 Lightning Damage', 'Lightning Resist 30%', 'Lightning Resist 35%', 21);
INSERT INTO RuneTable VALUES('Thul', 'Adds 3-14 Cold Damage - 3 Second Duration', 'Cold Resist 30%', 'Cold Resist 35%', 23);
INSERT INTO RuneTable VALUES('Amn', '7% Life Stolen Per Hit', 'Attacker Takes Damage of 14', 'Attacker Takes Damage of 14', 25);
INSERT INTO RuneTable VALUES('Sol', '+9 To Minimum Damage', 'Damage Reduced By 7', 'Damage Reduced By 7', 27);
INSERT INTO RuneTable VALUES('Shael', '20% Increased Attack Speed', '20% Faster Hit Recovery', '20% Faster Block Rate', 29);
INSERT INTO RuneTable VALUES('Dol', 'Hit Causes Monster To Flee 25%', 'Replenish Life +7', 'Replenish Life +7', 31);
INSERT INTO RuneTable VALUES('Hel', 'Requirements -20%', 'Requirements -15%', 'Requirements -15%', 0);
INSERT INTO RuneTable VALUES('Io', '+10 To Vitality', '+10 To Vitality', '+10 To Vitality', 35);
INSERT INTO RuneTable VALUES('Lum', '+10 To Energy', '+10 To Energy', '+10 To Energy', 37);
INSERT INTO RuneTable VALUES('Ko', '+10 To Dexterity', '+10 To Dexterity', '+10 To Dexterity', 39);
INSERT INTO RuneTable VALUES('Fal', '+10 To Strength', '+10 To Strength', '+10 To Strength', 41);
INSERT INTO RuneTable VALUES('Lem', '75% Extra Gold From Monsters', '50% Extra Gold From Monsters', '50% Extra Gold From Monsters', 43);
INSERT INTO RuneTable VALUES('Pul', '+75% Damage To Demons, +100 Attack Rating Against Demons', '30% Enhanced Defense', '30% Enhanced Defense', 45);
INSERT INTO RuneTable VALUES('Um', '25% Chance of Open Wounds', 'All Resistances +15', 'All Resistances +22', 47);
INSERT INTO RuneTable VALUES('Mal', 'Prevent Monster Heal', 'Magic Damage Reduced By 7', 'Magic Damage Reduced By 7', 49);
INSERT INTO RuneTable VALUES('Ist', '30% Better Chance of Getting Magic Items', '25% Better Chance of Getting Magic Items', '25% Better Chance of Getting Magic Items', 51);
INSERT INTO RuneTable VALUES('Gul', '20% Bonus To Attack Rating', '5% To Maximum Poison Resist', '5% To Maximum Poison Resist', 53);
INSERT INTO RuneTable VALUES('Vex', '7% Mana Stolen Per Hit', '5% To Maximum Fire Resist', '5% To Maximum Fire Resist', 55);
INSERT INTO RuneTable VALUES('Ohm', '+50% Enhanced Damage', '5% To Maximum Cold Resist', '5% To Maximum Cold Resist', 57);
INSERT INTO RuneTable VALUES('Lo', '20% Deadly Strike', '5% To Maximum Lightning Resist', '5% To Maximum Lightning Resist', 59);
INSERT INTO RuneTable VALUES('Sur', 'Hit Blinds Target', 'Maximum Mana 5%', '+50 To Mana', 61);
INSERT INTO RuneTable VALUES('Ber', '20% Chance of Crushing Blow', 'Damage Reduced by 8%', 'Damage Reduced by 8%', 63);
INSERT INTO RuneTable VALUES('Jah', 'Ignore Target'||chr(39)||'s Defense', 'Increase Maximum Life 5%', '+50 Life', 65);
INSERT INTO RuneTable VALUES('Cham', 'Freeze Target +3', 'Cannot Be Frozen', 'Cannot Be Frozen', 67);
INSERT INTO RuneTable VALUES('Zod', 'Indestructible', 'Indestructible', 'Indestructible', 69);

INSERT INTO RingTable VALUES('Nagelring', 7);
INSERT INTO MagicPropertyTable VALUES('Nagelring', 'Magic Damage Reduced By 3');
INSERT INTO MagicPropertyTable VALUES('Nagelring', '+50-75 To Attack Rating');
INSERT INTO MagicPropertyTable VALUES('Nagelring', 'Attacker Takes Damage of 3');
INSERT INTO MagicPropertyTable VALUES('Nagelring', '15-30% Better Chance Of Getting Magic Item');
INSERT INTO RingTable VALUES('Manald Heal', 15);
INSERT INTO MagicPropertyTable VALUES('Manald Heal', '4-7% Mana Stolen Per Hit');
INSERT INTO MagicPropertyTable VALUES('Manald Heal', 'Replenish Life +5-8');
INSERT INTO MagicPropertyTable VALUES('Manald Heal', 'Renegerate Mana 20%');
INSERT INTO MagicPropertyTable VALUES('Manald Heal', '+20 To Life');
INSERT INTO RingTable VALUES('Stone of Jordan', 29);
INSERT INTO MagicPropertyTable VALUES('Stone of Jordan', '+1 To All Skill Levels');
INSERT INTO MagicPropertyTable VALUES('Stone of Jordan', 'Increase Maximum Mana 25%');
INSERT INTO MagicPropertyTable VALUES('Stone of Jordan', 'Adds 1-12 Lightning Damage');
INSERT INTO MagicPropertyTable VALUES('Stone of Jordan', '+20 To Mana');
INSERT INTO RingTable VALUES('Dwarf Star', 45);
INSERT INTO MagicPropertyTable VALUES('Dwarf Star', 'Fire Absorb 15%');
INSERT INTO MagicPropertyTable VALUES('Dwarf Star', 'Heal Stamina Plus 15%');
INSERT INTO MagicPropertyTable VALUES('Dwarf Star', '+40 Maximum Stamina');
INSERT INTO MagicPropertyTable VALUES('Dwarf Star', '+40 Life');
INSERT INTO MagicPropertyTable VALUES('Dwarf Star', '100% Extra Gold From Monsters');
INSERT INTO MagicPropertyTable VALUES('Dwarf Star', 'Magic Damage Reduced By 12-15');
INSERT INTO RingTable VALUES('Raven Frost', 45);
INSERT INTO MagicPropertyTable VALUES('Raven Frost', '+150-250 To Attack Rating');
INSERT INTO MagicPropertyTable VALUES('Raven Frost', 'Adds 15-45 Cold Damage, 4 sec. Duration');
INSERT INTO MagicPropertyTable VALUES('Raven Frost', 'Cannot Be Frozen');
INSERT INTO MagicPropertyTable VALUES('Raven Frost', '+15-20 To Dexterity');
INSERT INTO MagicPropertyTable VALUES('Raven Frost', '+40 To Mana');
INSERT INTO MagicPropertyTable VALUES('Raven Frost', 'Cold Absorb 20%');
INSERT INTO RingTable VALUES('Bul-Kathos Wedding Band', 58);
INSERT INTO MagicPropertyTable VALUES('Bul-Kathos Wedding Band', '+1 To All Skill Levels');
INSERT INTO MagicPropertyTable VALUES('Bul-Kathos Wedding Band', '+(0.5 Per Character Level) 0-49 To Life');
INSERT INTO MagicPropertyTable VALUES('Bul-Kathos Wedding Band', '3-5% Life Stolen Per Hit');
INSERT INTO MagicPropertyTable VALUES('Bul-Kathos Wedding Band', '+50 Maximum Stamina');
INSERT INTO RingTable VALUES('Carrion Wind', 60);
INSERT INTO MagicPropertyTable VALUES('Carrion Wind', '10% Chance To Cast Level 10 Poison Nova When Struck');
INSERT INTO MagicPropertyTable VALUES('Carrion Wind', '8% Chance To Cast Level 13 Twister On Striking');
INSERT INTO MagicPropertyTable VALUES('Carrion Wind', '6-9% Life Stolen Per Hit');
INSERT INTO MagicPropertyTable VALUES('Carrion Wind', '+100-160 Defense Vs. Missile');
INSERT INTO MagicPropertyTable VALUES('Carrion Wind', 'Poison Resist +55%');
INSERT INTO MagicPropertyTable VALUES('Carrion Wind', '10% Damage Taken Goes To Mana');
INSERT INTO MagicPropertyTable VALUES('Carrion Wind', 'Level 21 Poison Creeper (15 Charges)');
INSERT INTO RingTable VALUES('Natures Peace', 69);
INSERT INTO MagicPropertyTable VALUES('Natures Peace', 'Slain Monsters Rest In Peace');
INSERT INTO MagicPropertyTable VALUES('Natures Peace', 'Prevent Monster Heal');
INSERT INTO MagicPropertyTable VALUES('Natures Peace', 'Poison Resist +20-30%');
INSERT INTO MagicPropertyTable VALUES('Natures Peace', 'Damage Reduced by 7-11');
INSERT INTO MagicPropertyTable VALUES('Natures Peace', 'Level 5 Oak Sage (27 charges)');
INSERT INTO RingTable VALUES('Wisp Projector', 76);
INSERT INTO MagicPropertyTable VALUES('Wisp Projector', '10% Chance To Cast Level 16 Lightning On Striking');
INSERT INTO MagicPropertyTable VALUES('Wisp Projector', 'Lightning Absorb 10-20%');
INSERT INTO MagicPropertyTable VALUES('Wisp Projector', '10-20% Better Chance of Getting Magic Items');
INSERT INTO MagicPropertyTable VALUES('Wisp Projector', 'Level 7 Spirit of Barbs (11 charges');
INSERT INTO MagicPropertyTable VALUES('Wisp Projector', 'Level 5 Heart of Wolverine (13 charges)');
INSERT INTO MagicPropertyTable VALUES('Wisp Projector', 'Level 2 Oak Sage (15 charges)');

INSERT INTO CharmTable VALUES('Small', 'Annihilus', 70);
INSERT INTO MagicPropertyTable VALUES('Annihilus', '+1 To All Skills');
INSERT INTO MagicPropertyTable VALUES('Annihilus', '+10-20 To All Attributes');
INSERT INTO MagicPropertyTable VALUES('Annihilus', 'All Resistances +10-20');
INSERT INTO MagicPropertyTable VALUES('Annihilus', '+5-10% To Experience Gained');
INSERT INTO CharmTable VALUES('Grand', 'Gheeds Fortune', 62);
INSERT INTO MagicPropertyTable VALUES('Gheeds Fortune', '80-160% Extra Gold From Monsters');
INSERT INTO MagicPropertyTable VALUES('Gheeds Fortune', 'Reduces All Vendor Prices 10-15%');
INSERT INTO MagicPropertyTable VALUES('Gheeds Fortune', '20-40% Better Chance of Getting Magic Items');

INSERT INTO AmuletTable VALUES('Nokozan Relic', 10);
INSERT INTO MagicPropertyTable VALUES('Nokozan Relic', '20% Faster Hit Recovery');
INSERT INTO MagicPropertyTable VALUES('Nokozan Relic', 'Fire Resist +50%');
INSERT INTO MagicPropertyTable VALUES('Nokozan Relic', '+10% To Maximum Fire Resist');
INSERT INTO MagicPropertyTable VALUES('Nokozan Relic', 'Adds 3-6 Fire Damage');
INSERT INTO MagicPropertyTable VALUES('Nokozan Relic', '+3 To Light Radius');
INSERT INTO AmuletTable VALUES('The Eye of Etlich', 15);
INSERT INTO MagicPropertyTable VALUES('The Eye of Etlich', '+1-5 To Light Radius');
INSERT INTO MagicPropertyTable VALUES('The Eye of Etlich', '+1 To All Skill Levels');
INSERT INTO MagicPropertyTable VALUES('The Eye of Etlich', '3-7% Life Stolen Per Hit');
INSERT INTO MagicPropertyTable VALUES('The Eye of Etlich', 'Adds (1-2) to (3-5) Cold Damage');
INSERT INTO MagicPropertyTable VALUES('The Eye of Etlich', 'Cold Duration: 2-10 Seconds');
INSERT INTO MagicPropertyTable VALUES('The Eye of Etlich', '+10-40 Defense vs. Missile');
INSERT INTO AmuletTable VALUES('The Mahim-Oak Curio', 25);
INSERT INTO MagicPropertyTable VALUES('The Mahim-Oak Curio', '+10 Defense');
INSERT INTO MagicPropertyTable VALUES('The Mahim-Oak Curio', '+10% Enhanced Defense');
INSERT INTO MagicPropertyTable VALUES('The Mahim-Oak Curio', '+10% Bonus To Attack Rating');
INSERT INTO MagicPropertyTable VALUES('The Mahim-Oak Curio', 'All Resistances +10');
INSERT INTO MagicPropertyTable VALUES('The Mahim-Oak Curio', '+10 To All Attributes');
INSERT INTO AmuletTable VALUES('Saracens Chance', 47);
INSERT INTO MagicPropertyTable VALUES('Saracens Chance', '10% Chance To Cast Level 2 Iron Maiden When Struck');
INSERT INTO MagicPropertyTable VALUES('Saracens Chance', 'All Resistances +15-25');
INSERT INTO MagicPropertyTable VALUES('Saracens Chance', '+12 To All Attributes');
INSERT INTO AmuletTable VALUES('The Cats Eye', 50);
INSERT INTO MagicPropertyTable VALUES('The Cats Eye', '30% Faster Run/Walk');
INSERT INTO MagicPropertyTable VALUES('The Cats Eye', '20% Increased Attack Speed');
INSERT INTO MagicPropertyTable VALUES('The Cats Eye', '+100 Defense vs. Missiles');
INSERT INTO MagicPropertyTable VALUES('The Cats Eye', '+100 Defense');
INSERT INTO MagicPropertyTable VALUES('The Cats Eye', '+25 To Dexterity');
INSERT INTO AmuletTable VALUES('Crescent Moon', 50);
INSERT INTO MagicPropertyTable VALUES('Crescent Moon', '10% Damage Taken Goes To Mana');
INSERT INTO MagicPropertyTable VALUES('Crescent Moon', '+45 To Mana');
INSERT INTO MagicPropertyTable VALUES('Crescent Moon', '3-6% Life Stolen Per Hit');
INSERT INTO MagicPropertyTable VALUES('Crescent Moon', '11-15% Mana Stolen Per Hit');
INSERT INTO MagicPropertyTable VALUES('Crescent Moon', 'Magic Damage Reduced By 10');
INSERT INTO MagicPropertyTable VALUES('Crescent Moon', '-2 To Light Radius');
INSERT INTO AmuletTable VALUES('Atmas Scarab', 60);
INSERT INTO MagicPropertyTable VALUES('Atmas Scarab', '5% Chance To Cast Level 2 Amplify Damage On Striking');
INSERT INTO MagicPropertyTable VALUES('Atmas Scarab', '20% Bonus To Attack Rating');
INSERT INTO MagicPropertyTable VALUES('Atmas Scarab', '+40 Poison Damage over 4 seconds');
INSERT INTO MagicPropertyTable VALUES('Atmas Scarab', 'Poison Resist +75%');
INSERT INTO MagicPropertyTable VALUES('Atmas Scarab', '+3 To Light Radius');
INSERT INTO MagicPropertyTable VALUES('Atmas Scarab', 'Attacker Takes Damage of 5');
INSERT INTO AmuletTable VALUES('The Rising Sun', 65);
INSERT INTO MagicPropertyTable VALUES('The Rising Sun', '+2 To Fire Skills');
INSERT INTO MagicPropertyTable VALUES('The Rising Sun', '2% Chance To Cast Level 13-19 Meteor When Struck');
INSERT INTO MagicPropertyTable VALUES('The Rising Sun', '+ (0.75 Per Character Level) 0-74 Fire Absorb');
INSERT INTO MagicPropertyTable VALUES('The Rising Sun', 'Adds 24-48 Fire Damage');
INSERT INTO MagicPropertyTable VALUES('The Rising Sun', 'Replenish Life +10');
INSERT INTO MagicPropertyTable VALUES('The Rising Sun', '+4 To Light Radius');
INSERT INTO AmuletTable VALUES('Highlords Wrath', 65);
INSERT INTO MagicPropertyTable VALUES('Highlords Wrath', '+1 To All Skill Levels');
INSERT INTO MagicPropertyTable VALUES('Highlords Wrath', '20% Increased Attack Speed');
INSERT INTO MagicPropertyTable VALUES('Highlords Wrath', '+ (0.375 Per Character Level) 0-37 % Deadly Strike');
INSERT INTO MagicPropertyTable VALUES('Highlords Wrath', 'Lightning Resist +35%');
INSERT INTO MagicPropertyTable VALUES('Highlords Wrath', 'Adds 1-30 Lightning Damage');
INSERT INTO MagicPropertyTable VALUES('Highlords Wrath', 'Attacker Takes Lightning Damage Of 15');
INSERT INTO AmuletTable VALUES('Maras Kaleidoscope', 67);
INSERT INTO MagicPropertyTable VALUES('Maras Kaleidoscope', '+2 To All Skill Levels');
INSERT INTO MagicPropertyTable VALUES('Maras Kaleidoscope', 'All Resistances +20-30');
INSERT INTO MagicPropertyTable VALUES('Maras Kaleidoscope', '+5 To All Attributes');
INSERT INTO AmuletTable VALUES('Seraphs Hymn', 65);
INSERT INTO MagicPropertyTable VALUES('Seraphs Hymn', '+2 To All Skill Levels');
INSERT INTO MagicPropertyTable VALUES('Seraphs Hymn', '+1-2 To Defensive Auras (Paladin Only)');
INSERT INTO MagicPropertyTable VALUES('Seraphs Hymn', '+20-50% Damage To Demons');
INSERT INTO MagicPropertyTable VALUES('Seraphs Hymn', '+150-250 To Attack Rating Against Demons');
INSERT INTO MagicPropertyTable VALUES('Seraphs Hymn', '+20-50% To Undead');
INSERT INTO MagicPropertyTable VALUES('Seraphs Hymn', '+150-250 To Attack Rating Against Undead');
INSERT INTO MagicPropertyTable VALUES('Seraphs Hymn', '+2 To Light Radius');
INSERT INTO AmuletTable VALUES('Metalgrid', 81);
INSERT INTO MagicPropertyTable VALUES('Metalgrid', '+400-450 To Attack Rating');
INSERT INTO MagicPropertyTable VALUES('Metalgrid', 'Level 22 Iron Golem (11 Charges)');
INSERT INTO MagicPropertyTable VALUES('Metalgrid', 'Level 12 Iron Maiden (20 Charges)');
INSERT INTO MagicPropertyTable VALUES('Metalgrid', 'All Resistances +25-35');
INSERT INTO MagicPropertyTable VALUES('Metalgrid', '+300-350 Defense');

INSERT INTO JewelTable VALUES('Rainbow Facet (Red1)', 49);
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Red1)', '100% Chance To Cast Level 29 Blaze When You Level-Up');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Red1)', 'Adds 17-45 Fire Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Red1)', '+3-5% To Fire Skill Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Red1)', '-(3-5)% To Enemy Fire Resistance');
INSERT INTO JewelTable VALUES('Rainbow Facet (Blue1)', 49);
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Blue1)', '100% Chance To Cast Level 43 Frost Nova When You Level-Up');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Blue1)', 'Adds 24-38 Cold Damage, 0.12 sec Duration (Normal)');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Blue1)', '+3-5% To Cold Skill Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Blue1)', '-(3-5)% To Enemy Cold Resistance');
INSERT INTO JewelTable VALUES('Rainbow Facet (White1)', 49);
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (White1)', '100% Chance To Cast Level 41 Nova When You Level-Up');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (White1)', 'Adds 1-74 Lightning Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (White1)', '+3-5% To Lightning Skill Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (White1)', '-(3-5)% To Enemy Lightning Resistance');
INSERT INTO JewelTable VALUES('Rainbow Facet (Green1)', 49);
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Green1)', '100% Chance To Cast Level 23 Venom When You Level-Up');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Green1)', 'Adds 37 Poison Damage Over 2 Seconds');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Green1)', '+3-5% To Poison Skill Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Green1)', '-(3-5)% To Enemy Poison Resistance');
INSERT INTO JewelTable VALUES('Rainbow Facet (Red2)', 49);
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Red2)', '100% Chance To Cast Level 31 Meteor When You Die');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Red2)', 'Adds 17-45 Fire Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Red2)', '+3-5% To Fire Skill Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Red2)', '-(3-5)% To Enemy Fire Resistance');
INSERT INTO JewelTable VALUES('Rainbow Facet (Blue2)', 49);
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Blue2)', '100% Chance To Cast Level 37 Blizzard When You Die');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Blue2)', 'Adds 24-38 Cold Damage, 0.12 sec Duration (Normal)');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Blue2)', '+3-5% To Cold Skill Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Blue2)', '-(3-5)% To Enemy Cold Resistance');
INSERT INTO JewelTable VALUES('Rainbow Facet (White2)', 49);
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (White2)', '100% Chance To Cast Level 47 Chain Lightning When You Die');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (White2)', 'Adds 1-74 Lightning Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (White2)', '+3-5% To Lightning Skill Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (White2)', '-(3-5)% To Enemy Lightning Resistance');
INSERT INTO JewelTable VALUES('Rainbow Facet (Green2)', 49);
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Green2)', '100% Chance To Cast Level 51 Poison Nova When You Die');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Green2)', 'Adds 37 Poison Damage Over 2 Seconds');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Green2)', '+3-5% To Poison Skill Damage');
INSERT INTO MagicPropertyTable VALUES('Rainbow Facet (Green2)', '-(3-5)% To Enemy Poison Resistance');

INSERT INTO CharmAffixTable VALUES('Prefix', 'Stout', '+1-8 Defense', 'Small', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Burly', '+15-20 Defense', 'Small', 28);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Stalwart', '+20-30 Defense', 'Small', 40);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Red', '+1 To Minimum Damage', 'Small', 90);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Jagged', '+1 To Maximum Damage', 'Small', 90);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Rugged', '+4-16 Max Stamina', 'Small', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Bronze', '+2-12 To Attack Rating', 'Small', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Iron', '+13-24 To Attack Rating', 'Small', 31);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Steel', '+25-36 To Attack Rating', 'Small', 49);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Fine', '+10-20 To Attack Rating, +1-3 To Maximum Damage', 'Small', 21);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Lizards', '+1-7 Mana', 'Small', 12);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Snakes', '+8-12 Mana', 'Small', 24);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Serpents', '+13-17 Mana', 'Small', 40);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shimmering', 'All Resistances +3-5%', 'Small', 25);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Azure', 'Resist Cold +3-5%', 'Small', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Lapis', 'Resist Cold +6-7%', 'Small', 10);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Cobalt', 'Resist Cold +8-9%', 'Small', 20);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Sapphire', 'Resist Cold +10-11%', 'Small', 32);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Russet', 'Resist Fire +3-5%', 'Small', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Garnet', 'Resist Fire +6-7%', 'Small', 10);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Ruby', 'Resist Fire +8-9%', 'Small', 20);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Crimson', 'Resist Fire +10-11%', 'Small', 32);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Tangerine', 'Resist Lightning +3-5%', 'Small', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Ocher', 'Resist Lightning +6-7%', 'Small', 10);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Coral', 'Resist Lightning +8-9%', 'Small', 20);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Amber', 'Resist Lightning +10-11%', 'Small', 32);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Beryl', 'Resist Poison +3-5%', 'Small', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Viridian', 'Resist Poison +6-7%', 'Small', 10);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Jade', 'Resist Poison +8-9%', 'Small', 20);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Emerald', 'Resist Poison +10-11%', 'Small', 32);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Snowflake', '+1-2 Minimum and +2-4 Maximum Cold Damage - 1 Second Duration', 'Small', 27);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shivering', '+3-4 Minimum and +5-8 Maximum Cold Damage - 1 Second Duration', 'Small', 42);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Boreal', '+5-7 Minimum and +9-14 Maximum Cold Damage - 1 Second Duration', 'Small', 66);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Hibernal', '+8-10 Minimum and +15-20 Maximum Cold Damage - 1 Second Duration', 'Small', 91);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Ember', '+1-2 Minimum and +2-3 Maximum Fire Damage', 'Small', 21);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Smoldering', '+2-3 Minimum and +4-10 Maximum Fire Damage', 'Small', 40);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Smoking', '+4-9 Minimum and +11-19 Maximum Fire Damage', 'Small', 64);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Flaming', '+10-19 Minimum and +20-29 Maximum Fire Damage', 'Small', 89);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Static', '+1 Minimum and +6-11 Maximum Lightning Damage', 'Small', 23);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Glowing', '+1 Minimum and +12-24 Maximum Lightning Damage', 'Small', 41);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Arcing', '+1 Minimum and +25-43 Maximum Lightning Damage', 'Small', 65);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shocking', '+1 Minimum and +44-71 Maximum Lightning Damage', 'Small', 90);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Septic', '+15 Poison Damage Over 3 Seconds', 'Small', 18);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Foul', '+50 Poison Damage Over 4 Seconds', 'Small', 39);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Toxic', '+100 Poison Damage Over 5 Seconds', 'Small', 63);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Pestilent', '+175 Poison Damage Over 6 Seconds', 'Small', 88);

INSERT INTO CharmAffixTable VALUES('Suffix', 'Craftsmanship', '+1 To Maximum Damage', 'Small', 85);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Balance', '5% Fast Hit Recovery', 'Small', 29);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Greed', '5-10% More Gold', 'Small', 15);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Fortune', '3-5% Better Chance Of Getting Magic Items', 'Small', 18);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Good Luck', '6-7% Better Chance Of Getting Magic Items', 'Small', 33);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Life', '+5-10 Life', 'Small', 14);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Substinence', '+11-15 Life', 'Small', 17);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Vita', '+16-20 Life', 'Small', 39);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Strength', '+1-2 To Strength', 'Small', 5);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Dexterity', '+1-2 To Dexterity', 'Small', 7);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Inertia', '3% Faster Run/Walk', 'Small', 36);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Blight', '+6 Poison Damage Over 3 Seconds', 'Small', 9);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Venom', '+15 Poison Damage Over 4 Seconds', 'Small', 20);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Pestilence', '+25 Poison Damage Over 5 Seconds', 'Small', 32);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Anthrax', '+50 Poison Damage Over 6 Seconds', 'Small', 44);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Frost', '+1 Minimum and +2 Maximum Cold Damage - 1 Second Duration', 'Small', 14);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Icicle', '+2 Minimum and +3-4 Maximum Cold Damage - 1 Second Duration', 'Small', 21);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Glacier', '+3 Minimum and +5-6 Maximum Cold Damage - 1 Second Duration', 'Small', 33);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Winter', '+4-5 Minimum and +7-9 Maximum Cold Damage - 1 Second Duration', 'Small', 46);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Flame', '+1 Minimum and +2 Maximum Fire Damage', 'Small', 11);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Fire', '+2 Minimum and +3-4 Maximum Fire Damage', 'Small', 20);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Burning', '+3-4 Minimum and +5-8 Maximum Fire Damage', 'Small', 32);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Incineration', '+5-7 Minimum and +9-13 Maximum Fire Damage', 'Small', 45);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Shock', '+1 Minimum and +3-6 Maximum Lightning Damage', 'Small', 12);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Lightning', '+1 Minimum and +7-10 Maximum Lightning Damage', 'Small', 21);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Thunder', '+1 Minimum and +11-18 Maximum Lightning Damage', 'Small', 33);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Storms', '+1 Minimum and +19-28 Maximum Lightning Damage', 'Small', 45);

INSERT INTO CharmAffixTable VALUES('Prefix', 'Stout', '+2-12 Defense', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Burly', '+13-30 Defense', 'Medium', 26);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Stalwart', '+30-60 Defense', 'Medium', 38);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Red', '+1 To Minimum Damage', 'Medium', 30);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Sanguinary', '+2 To Minimum Damage', 'Medium', 60);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Jagged', '+1 To Maximum Damage', 'Medium', 33);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Forked', '+2 To Maximum Damage', 'Medium', 52);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Rugged', '+8-32 Max Stamina', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Bronze', '+4-25 To Attack Rating', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Iron', '+39-51 To Attack Rating', 'Medium', 25);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Steel', '+52-64 To Attack Rating', 'Medium', 44);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Fine', '+10-20 To Attack Rating, +1-3 To Maximum Damage', 'Medium', 19);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Sharp', '+21-48 To Attack Rating, +4-6 To Maximum Damage', 'Medium', 28);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Lucky', '1-6% Better Chance Of Getting Magic Items', 'Medium', 34);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Lizards', '+2-12 Mana', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Snakes', '+13-23 Mana', 'Medium', 23);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Serpents', '+24-34 Mana', 'Medium', 41);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shimmering', 'All Resistances +3-8%', 'Medium', 17);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Azure', 'Resist Cold +4-7%', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Lapis', 'Resist Cold +8-10%', 'Medium', 16);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Cobalt', 'Resist Cold +11-12%', 'Medium', 25);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Sapphire', 'Resist Cold +13-15%', 'Medium', 35);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Crimson', 'Resist Fire +4-7%', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Russet', 'Resist Fire +8-10%', 'Medium', 16);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Garnet', 'Resist Fire +11-12%', 'Medium', 25);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Ruby', 'Resist Fire +13-15%', 'Medium', 35);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Tangerine', 'Resist Lightning +4-7%', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Ocher', 'Resist Lightning +8-10%', 'Medium', 16);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Coral', 'Resist Lightning +11-12%', 'Medium', 25);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Amber', 'Resist Lightning +13-15%', 'Medium', 35);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Beryl', 'Resist Poison +4-7%', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Viridian', 'Resist Poison +8-10%', 'Medium', 16);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Jade', 'Resist Poison +11-12%', 'Medium', 25);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Emerald', 'Resist Poison +13-15%', 'Medium', 35);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Septic', '+10 Poison Damage Over 3 Seconds', 'Medium', 9);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Foul', '+30 Poison Damage Over 4 Seconds', 'Medium', 26);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Toxic', '+90 Poison Damage Over 5 Seconds', 'Medium', 46);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Pestilent', '+175 Poison Damage Over 6 Seconds', 'Medium', 66);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Snowflake', '+2-3 Minimum and +3-5 Maximum Cold Damage - 1 Second Duration', 'Medium', 18);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shivering', '+4-5 Minimum and +6-10 Maximum Cold Damage - 1 Second Duration', 'Medium', 29);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Boreal', '+6-10 Minimum and +11-20 Maximum Cold Damage - 1 Second Duration', 'Medium', 49);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Hibernal', '+11-15 Minimum and +21-30 Maximum Cold Damage - 1 Second Duration', 'Medium', 69);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Ember', '+1 Minimum and +2-3 Maximum Fire Damage', 'Medium', 13);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Smoldering', '+2-3 Minimum and +4-12 Maximum Fire Damage', 'Medium', 27);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Smoking', '+4-9 Minimum and +13-27 Maximum Fire Damage', 'Medium', 47);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Flaming', '+10-27 Minimum and +28-43 Maximum Fire Damage', 'Medium', 67);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Static', '+1 Minimum and +5-9 Maximum Lightning Damage', 'Medium', 14);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Glowing', '+1 Minimum and +10-26 Maximum Lightning Damage', 'Medium', 28);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Arcing', '+1 Minimum and +27-58 Maximum Lightning Damage', 'Medium', 48);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shocking', '+1 Minimum and +59-90 Maximum Lightning Damage', 'Medium', 68);

INSERT INTO CharmAffixTable VALUES('Suffix', 'Craftsmanship', '+1 To Maximum Damage', 'Medium', 26);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Quality', '+2 To Maximum Damage', 'Medium', 56);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Dexterity', '+2-5 To Dexterity', 'Medium', 3);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Balance', '8% Fast Hit Recovery', 'Medium', 19);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Greed', '5-22% More Gold', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Life', '+6-15 Life', 'Medium', 1);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Substinence', '+16-25 Life', 'Medium', 26);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Vita', '+26-35 Life', 'Medium', 58);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Strength', '+2-5 To Strength', 'Medium', 3);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Inertia', '5% Faster Run/Walk', 'Medium', 24);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Blight', '+6 Poison Damage Over 3 Seconds', 'Medium', 5);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Venom', '+15 Poison Damage Over 4 Seconds', 'Medium', 20);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Pestilence', '+25 Poison Damage Over 5 Seconds', 'Medium', 23);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Anthrax', '+50 Poison Damage Over 6 Seconds', 'Medium', 33);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Frost', '+1 Minimum and +2-3 Maximum Cold Damage - 1 Second Duration', 'Medium', 9);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Icicle', '+2 Minimum and +4-5 Maximum Cold Damage - 1 Second Duration', 'Medium', 15);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Glacier', '+3 Minimum and +6-8 Maximum Cold Damage - 1 Second Duration', 'Medium', 25);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Winter', '+4-6 Minimum and +9-12 Maximum Cold Damage - 1 Second Duration', 'Medium', 35);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Flame', '+1 Minimum and +2 Maximum Fire Damage', 'Medium', 7);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Fire', '+2 Minimum and +3-5 Maximum Fire Damage', 'Medium', 14);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Burning', '+3-5 Minimum and +6-11 Maximum Fire Damage', 'Medium', 24);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Incineration', '+6-10 Minimum and +12-17 Maximum Fire Damage', 'Medium', 34);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Shock', '+1 Minimum and +3-5 Maximum Lightning Damage', 'Medium', 7);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Lightning', '+1 Minimum and +6-13 Maximum Lightning Damage', 'Medium', 14);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Thunder', '+1 Minimum and +14-25 Maximum Lightning Damage', 'Medium', 24);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Storms', '+1 Minimum and +26-38 Maximum Lightning Damage', 'Medium', 34);

INSERT INTO CharmAffixTable VALUES('Prefix', 'Stout', '+3-12 Defense', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Burly', '+13-30 Defense', 'Large', 17);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Stalwart', '+33-100 Defense', 'Large', 32);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Red', '+1 To Minimum Damage', 'Large', 15);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Sanguinary', '+2 To Minimum Damage', 'Large', 45);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Bloody', '+3 To Minimum Damage', 'Large', 75);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Jagged', '+1 To Maximum Damage', 'Large', 7);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Forked', '+2 To Maximum Damage', 'Large', 37);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Serrated', '+3 To Maximum Damage', 'Large', 67);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Rugged', '+12-50 Max Stamina', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Bronze', '+6-42 To Attack Rating', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Iron', '+43-87 To Attack Rating', 'Large', 19);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Steel', '+88-132 To Attack Rating', 'Large', 37);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Fine', '+10-48 To Attack Rating, +1-6 To Maximum Damage', 'Large', 15);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Sharp', '+49-76 To Attack Rating, +7-10 To Maximum Damage', 'Large', 29);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Lucky', '1-12% Better Chance Of Getting Magic Items', 'Large', 21);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Lizards', '+3-20 Mana', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Snakes', '+21-39 Mana', 'Large', 19);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Serpents', '+40-59 Mana', 'Large', 37);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shimmering', 'All Resistances +3-15%', 'Large', 8);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Azure', 'Resist Cold +7-15%', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Lapis', 'Resist Cold +16-20%', 'Large', 10);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Cobalt', 'Resist Cold +21-25%', 'Large', 20);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Sapphire', 'Resist Cold +26-30%', 'Large', 30);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Crimson', 'Resist Fire +7-15%', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Russet', 'Resist Fire +16-20%', 'Large', 10);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Garnet', 'Resist Fire +21-25%', 'Large', 20);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Ruby', 'Resist Fire +26-30%', 'Large', 30);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Tangerine', 'Resist Lightning +7-15%', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Ocher', 'Resist Lightning +16-20%', 'Large', 10);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Coral', 'Resist Lightning +21-25%', 'Large', 20);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Amber', 'Resist Lightning +26-30%', 'Large', 30);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Beryl', 'Resist Poison +7-15%', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Viridian', 'Resist Poison +16-20%', 'Large', 10);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Jade', 'Resist Poison +21-25%', 'Large', 20);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Emerald', 'Resist Poison +26-30%', 'Large', 30);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Fletchers', '+1 Amazon Bow and Crossbow Skills', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Acrobats', '+1 Amazon Passive Skills', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Harpoonists', '+1 Amazon Javelin and Spear Skills', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Burning', '+1 Sorceress Fire Skills', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Sparking', '+1 Sorceress Lightning Skills', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Chilling', '+1 Sorceress Cold Skills', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Hexing', '+1 Necromancer Curses', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Fungal', '+1 Necromancer Poison and Bone Spells', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Graverobbers', '+1 Necromancer Summoning Spells', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Lion Branded', '+1 Paladin Combat Skills', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Captains', '+1 Paladin Offensive Auras', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Preservers', '+1 Paladin Defensive Auras', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Experts', '+1 Barbarian Combat Skills', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Fanatic', '+1 Barbarian Combat Masteries', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Sounding', '+1 Barbarian Warcries', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Trainers', '+1 Druid Summoning', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Spritual', '+1 Druid Shapeshifting', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Natures', '+1 Druid Elemental', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Entrapping', '+1 Assassin Traps', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Mentalists', '+1 Assassin Shadow Disciplines', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shogukushas', '+1 Assassin Martial Arts', 'Large', 50);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Septic', '+5 Poison Damage Over 3 Seconds', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Foul', '+15 Poison Damage Over 4 Seconds', 'Large', 12);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Toxic', '+50 Poison Damage Over 5 Seconds', 'Large', 27);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Pestilent', '+100 Poison Damage Over 6 Seconds', 'Large', 42);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Snowy', '+1 Minimum and +2-3 Maximum Cold Damage - 1 Second Duration', 'Large', 9);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shivering', '+2-4 Minimum and +4-8 Maximum Cold Damage - 1 Second Duration', 'Large', 15);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Boreal', '+5-7 Minimum and +9-15 Maximum Cold Damage - 1 Second Duration', 'Large', 30);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Hibernal', '+8-13 Minimum and +16-25 Maximum Cold Damage - 1 Second Duration', 'Large', 45);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Ember', '+1 Minimum and +2-3 Maximum Fire Damage', 'Large', 5);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Smoldering', '+2-3 Minimum and +4-7 Maximum Fire Damage', 'Large', 15);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Smoking', '+4-7 Minimum and +8-19 Maximum Fire Damage', 'Large', 28);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Flaming', '+8-18 Minimum and +20-36 Maximum Fire Damage', 'Large', 43);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Static', '+1 Minimum and +4-5 Maximum Lightning Damage', 'Large', 7);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Glowing', '+1 Minimum and +6-17 Maximum Lightning Damage', 'Large', 14);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Arcing', '+1 Minimum and +18-44 Maximum Lightning Damage', 'Large', 29);
INSERT INTO CharmAffixTable VALUES('Prefix', 'Shocking', '+1 Minimum and +45-79 Maximum Lightning Damage', 'Large', 44);

INSERT INTO CharmAffixTable VALUES('Suffix', 'Craftsmanship', '+1 To Maximum Damage', 'Large', 85);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Quality', '+2 To Maximum Damage', 'Large', 41);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Maiming', '+3-4 To Maximum Damage', 'Large', 71);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Dexterity', '+3-6 To Dexterity', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Balance', '12% Fast Hit Recovery', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Greed', '10-40% More Gold', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Life', '+5-20 Life', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Substinence', '+21-35 Life', 'Large', 31);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Vita', '+36-50 Life', 'Large', 77);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Strength', '+3-6 To Strength', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Inertia', '7% Faster Run/Walk', 'Large', 19);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Blight', '+6 Poison Damage Over 3 Seconds', 'Large', 1);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Venom', '+15 Poison Damage Over 4 Seconds', 'Large', 6);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Pestilence', '+25 Poison Damage Over 5 Seconds', 'Large', 14);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Anthrax', '+50 Poison Damage Over 6 Seconds', 'Large', 21);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Frost', '+1 Minimum and +2 Maximum Cold Damage - 1 Second Duration', 'Large', 5);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Icicle', '+2 Minimum and +3-4 Maximum Cold Damage - 1 Second Duration', 'Large', 8);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Glacier', '+3 Minimum and +5-7 Maximum Cold Damage - 1 Second Duration', 'Large', 15);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Winter', '+4-6 Minimum and +8-11 Maximum Cold Damage - 1 Second Duration', 'Large', 23);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Flame', '+1 Minimum and +2 Maximum Fire Damage', 'Large', 3);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Fire', '+1-2 Minimum and +3 Maximum Fire Damage', 'Large', 8);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Burning', '+2-3 Minimum and +4-7 Maximum Fire Damage', 'Large', 14);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Incineration', '+6-10 Minimum and +12-17 Maximum Fire Damage', 'Large', 22);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Shock', '+1 Minimum and +2-3 Maximum Lightning Damage', 'Large', 4);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Lightning', '+1 Minimum and +4-7 Maximum Lightning Damage', 'Large', 7);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Thunder', '+1 Minimum and +8-21 Maximum Lightning Damage', 'Large', 15);
INSERT INTO CharmAffixTable VALUES('Suffix', 'Storms', '+1 Minimum and +22-33 Maximum Lightning Damage', 'Large', 22);

INSERT INTO JewelAffixTable VALUES('Prefix', 'Blanched', '+5-8 Defense', 1);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Eburin', '+9-20 Defense', 16);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Bone', '+21-40 Defense', 32);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Ivory', '+41-64 Defense', 64);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Scarlet', '+1-4 To Minimum Damage', 8);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Crimson', '+5-8 To Minimum Damage', 38);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Carbuncle', '+1-5 To Maximum Damage', 12);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Carmine', '+6-9 To Maximum Damage', 35);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Vermillion', '+11-15 To Maximum Damage', 58);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Cinnabar', '+5-10% Damage', 1);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Rusty', '+11-20% Damage', 13);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Realgar', '+21-30% Damage', 45);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Ruby1', '+31-40% Damage', 66);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Dun', '+7-12% Damage Goes To Mana Damage', 7);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Brown', 'Heal Stamina Plus +10-15%', 39);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Chestnut', '+10-15 Max Stamina', 1);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Maroon', '+16-25 Max Stamina', 17);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Nickel', '+10-20 To Attack Rating', 1);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Tin', '+21-40 To Attack Rating', 8);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Silver', '+41-60 To Attack Rating', 25);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Argent', '+60-100 To Attack Rating', 44);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Bright', '+1 To Light Radius', 1);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Emerald', '+3-7% Better Chance Of Getting Magic Items', 25);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Zircon', '+5-10 Mana', 3);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Jacinth', '+11-15 Mana', 17);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Turqoise', '+16-20 Mana', 29);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Shimmering', 'All Resistances +5-10', 16);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Scintillating', 'All Resistances +11-15', 34);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Lapis Lazuli', 'Resist Cold +5-15%', 2);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Sapphire', 'Resist Cold +16-30%', 19);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Garnet', 'Resist Fire +5-15%', 2);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Ruby2', 'Resist Fire +16-30%', 18);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Camphor', 'Resist Lightning +5-15%', 2);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Ambergris', 'Resist Lightning +16-30%', 19);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Beryl', 'Resist Poison +5-15%', 2);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Jade', 'Resist Poison +16-30%', 19);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Aureolin', '+1-3 Mana Per Kill', 22);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Diamond', '+25-50 To Attack Rating vs Demons, +25-40% Damage vs Demons', 26);
INSERT INTO JewelAffixTable VALUES('Prefix', 'Pearl', '+25-50 To Attack Rating vs Undead, +25-50% Damage vs Undead', 2);

INSERT INTO JewelAffixTable VALUES('Suffix', 'Malice', 'Attacker Takes Damage of 1-5', 37);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Fervor', '15% Increased Attack Spee', 39);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Frigidity', '1-5 Cold Damage - 2 Second Duration', 16);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Passion', '+1-3 Minimum Fire Damage And +6-10 Maximum Fire Damage', 15);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Ennui', '+1 Minimum And +10-20 Maximum Lightning Damage', 15);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Ire', '+2-5 To Maximum Damage', 4);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Wrath', '+6-9 To Maximum Damage', 11);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Carnage', '+11-15 To Maximum Damage', 25);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Joyfulness', '+1-4 To Minimum Damage', 5);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Bliss', '+5-10 To Minimum Damage', 43);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Envy', '+9 Minimum Poison Damage and +26 Maximum Poison Damage', 1);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Truth', '7% Faster Hit Recovery', 44);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Honor', 'Replenish Life +1-4', 47);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Avarice', '+10-30% More Gold', 1);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Prosperity', '+5-10% Better Chance Of Getting Magic Items', 26);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Spirit', '+3-8 To Life', 1);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Hope', '+3-8 To Life', 45);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Freedom', 'Requirements -15%', 1);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Icicle', '+2-3 Minimum and +6-10 Maximum Cold Damage - 3 Second Duration', 37);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Glacier', '+4-5 Minimum and +11-15 Maximum Cold Damage - 3 Second Duration', 58);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Fire', '+4-10 Minimum and +11-30 Maximum Fire Damage', 36);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Burning', '+11-25 Minimum and +35-50 Maximum Fire Damage', 57);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Lightning', '+1 Minimum and +21-60 Maximum Lightning Damage', 36);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Thunder', '+1 Minimum and +61-100 Maximum Lightning Damage', 57);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Daring', '+4-9 Dexterity', 19);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Knowledge', '+4-9 To Energy', 24);
INSERT INTO JewelAffixTable VALUES('Suffix', 'Virility', '+5-9 Strength', 33);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Bronze', '+10-20 to Attack Rating', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Iron', '+21-40 to Attack Rating', 4);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Steel', '+41-60 to Attack Rating', 8);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Silver', '+61-80 to Attack Rating', 12);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Gold', '+80-100 to Attack Rating', 17);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Platinum', '+101-120 to Attack Rating', 22);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Meteoric', '+121-150 to Attack Rating', 27);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Strange', '+151-300 to Attack Rating', 32);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Weird', '+301-450 to Attack Rating', 37);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating', 'Hawkeye', '+1.5[12]6-594 Attack Rating', 35);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Cold Damage', 'Snowy', '+6-9 Minimum and 19-30 Maximum Cold Damage - 1 sec Duration', 25);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Cold Damage', 'Shivering', '+10-15 Minimum and 31-45 Maximum Cold Damage - 2 sec Duration', 35);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Cold Damage', 'Boreal', '+16-23 Minimum and 46-90 Maximum Cold Damage - 3 sec Duration', 50);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Cold Damage', 'Hibernal', '+24-45 Minimum and 91-140 Maximum Cold Damage - 4 sec Duration', 70);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Fire Damage', 'Fiery', '+16-25 Minimum and 31-60 Maximum Fire Damage', 25);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Fire Damage', 'Smoldering', '+26-50 Minimum and 61-90 Maximum Fire Damage', 35);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Fire Damage', 'Smoking', '+51-80 Minimum and 91-130 Maximum Fire Damage', 47);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Fire Damage', 'Flaming', '+81-120 Minimum and 131-180 Maximum Fire Damage', 61);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Fire Damage', 'Condensing', '+121-170 Minimum and 181-240 Maximum Fire Damage', 77);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Lightning Damage', 'Static', '+1 Minimum and 49-120 Maximum Lightning Damage', 25);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Lightning Damage', 'Glowing', '+1 Minimum and 121-180 Maximum Lightning Damage', 34);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Lightning Damage', 'Buzzing', '+1 Minimum and 181-260 Maximum Lightning Damage', 46);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Lightning Damage', 'Arcing', '+1 Minimum and 261-360 Maximum Lightning Damage', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Lightning Damage', 'Shocking', '+1 Minimum and 361-480 Maximum Lightning Damage', 76);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Poison Damage', 'Septic', '+6 Poison Damage Over 2 Seconds', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Poison Damage', 'Foul', '+12 Poison Damage Over 3 Seconds', 10);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Poison Damage', 'Corrosive', '+80 Poison Damage Over 4 Seconds', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Poison Damage', 'Toxic', '+150 Poison Damage Over 5 Seconds', 35);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Poison Damage', 'Pestilent', '+275 Poison Damage Over 6 Seconds', 50);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Damage', 'Jagged', '+10-20% Damage', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Damage', 'Deadly', '+21-30% Damage', 5);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Damage', 'Vicious', '+31-40% Damage', 8);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Damage', 'Brutal', '+41-50% Damage', 14);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Damage', 'Massive', '+51-65% Damage', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Damage', 'Savage', '+66-80% Damage', 26);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Damage', 'Merciless', '+81-100% Damage', 32);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Damage', 'Ferocious', '+101-200% Damage', 41);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Damage', 'Cruel', '+201-300% Damage', 51);

INSERT INTO MagicAffixTable VALUES('Prefix', '+%Attack Rating', 'Visionary', '+(1 Per Character Level)1-99% To Attack Rating', 35);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating/Max Damage', 'Fools', '+(16.5 Per Character Level)16.5-1633.5 To Attack Rating/+(0.5 Per Character Level)0.5-49.5 To Maximum Damage', 50);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating/Max Damage', 'Screaming', '+(0.75 Per Character Level)0.75-74.25 To Maximum Damage', 50);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage', 'Sharp', '+10-20 to Attack Rating, Damage: +10-20%', 5);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage', 'Fine', '+21-40 to Attack Rating, Damage: +21-30%', 12);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage', 'Warriors', '+41-60 to Attack Rating, Damage: +31-40%', 19);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage', 'Soldiers', '+61-80 to Attack Rating, Damage: +41-50%', 27);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage', 'Knights', '+81-100 to Attack Rating, Damage: +51-65%', 38);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage', 'Lords', '+101-120 to Attack Rating, Damage: +66-80%', 47);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage', 'Kings', '+121-150 to Attack Rating, Damage: +81-100%', 56);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage', 'Masters', '+151-250 to Attack Rating, Damage: +101-150%', 56);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage', 'Grandmasters', '+251-300 to Attack Rating, Damage: +151-200%', 69);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Demons', 'Lunar', '+25-50 to Attack Rating vs Demons, Damage: +10-25% vs Demons', 3);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Demons', 'Arcadian', '+51-100 to Attack Rating vs Demons, Damage: +26-50% vs Demons', 15);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Demons', 'Unearthly', '+101-150 to Attack Rating vs Demons, Damage: +51-100% vs Demons', 25);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Demons', 'Astral', '+151-200 to Attack Rating vs Demons, Damage: +101-150% vs Demons', 35);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Demons', 'Elysian', '+201-300 to Attack Rating vs Demons, Damage: +151-200% vs Demons', 45);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Demons', 'Celestial', '+300-400 to Attack Rating vs Demons, Damage: +201-300% vs Demons', 55);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Undead', 'Consecrated', '+25-75 to Attack Rating vs Undead, Damage: +25-75% vs Undead', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Undead', 'Pure', '+76-175 to Attack Rating vs Undead, Damage: +76-125% vs Undead', 15);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Undead', 'Sacred', '+175-250 to Attack Rating vs Undead, Damage: +126-200% vs Undead', 25);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Undead', 'Hallowed', '+251-325 to Attack Rating vs Undead, Damage: +201-275% vs Undead', 35);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Attack Rating and +Damage vs Undead', 'Divine', '+326-450 to Attack Rating vs Undead, Damage: +276-350% vs Undead', 55);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Defense', 'Sturdy', '+10-30% Defense', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Defense', 'Strong', '+31-40% Defense', 9);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Defense', 'Glorious', '+41-50% Defense', 19);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Defense', 'Blessed', '+51-65% Defense', 25);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Defense', 'Saintly', '+66-80% Defense', 31);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Defense', 'Holy', '+81-100% Defense', 36);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Defense', 'Godly', '+101-200% Defense', 45);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Defense', 'Faithful', '+(3 Per Character Level)3-297 Defense/+(0.5 Per Character Level)0.5-49.5 Defense', 30);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Mana', 'Lizards', '+1-5 to Mana', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Mana', 'Snakes', '+5-10 to Mana', 6);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Mana', 'Serpents', '+11-20 to Mana', 14);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Mana', 'Drakes', '+21-30 to Mana', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Mana', 'Dragons', '+31-40 to Mana', 24);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Mana', 'Wryms', '+41-60 to Mana', 30);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Mana', 'Great Wyrms', '+61-90 to Mana', 37);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Mana', 'Bahamuts', '+91-120 to Mana', 45);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Mana', 'Mnemonic', '+(0.5 Per Character Level)0.5-49.5 Mana', 25);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Light Radius', 'Glimmering', '+1 to Light Radius', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Light Radius', 'Glowing', '+2 to Light Radius', 6);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Fire Resist', 'Crimson', 'Fire Resist +5-10%', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Fire Resist', 'Russet', 'Fire Resist +11-20%', 12);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Fire Resist', 'Garnet', 'Fire Resist +21-30%', 18);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Fire Resist', 'Ruby', 'Fire Resist +31-40%', 25);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Cold Resist', 'Azure', 'Cold Resist +5-10%', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Cold Resist', 'Lapis', 'Cold Resist +11-20%', 12);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Cold Resist', 'Cobalt', 'Cold Resist +21-30%', 18);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Cold Resist', 'Sapphire', 'Cold Resist +31-40%', 25);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Lightning Resist', 'Tangerine', 'Lightning Resist +5-10%', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Lightning Resist', 'Ocher', 'Lightning Resist +11-20%', 12);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Lightning Resist', 'Coral', 'Lightning Resist +21-30%', 18);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Lightning Resist', 'Amber', 'Lightning Resist +31-40%', 25);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Poison Resist', 'Beryl', 'Poison Resist +5-10%', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Poison Resist', 'Viridian', 'Poison Resist +11-20%', 12);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Poison Resist', 'Jade', 'Poison Resist +21-30%', 18);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Poison Resist', 'Emerald', 'Poison Resist +31-40%', 25);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Resist all', 'Shimmering', '+3-7% to each Resistance', 6);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Resist all', 'Rainbow', '+8-11% to each Resistance', 18);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Resist all', 'Scintillating', '+12-15% to each Resistance', 28);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Resist all', 'Prismatic', '+16-20% to each Resistance', 39);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Resist all', 'Chromatic', '+21-30% to each Resistance', 50);

INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Maidens', '+1 Amazon Skill Levels', 30);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Valkyries', '+2 Amazon Skill Levels', 50);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Slayer', '+1 Barbarian Skill Levels', 30);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Berserker', '+2 Barbarian Skill Levels', 50);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Monks', '+1 Paladin Skill Levels', 30);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Priests', '+2 Paladin Skill Levels', 50);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Summoners', '+1 Necromancer Skill Levels', 30);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Necromancers', '+2 Necromancer Skill Levels', 50);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Angels', '+1 Sorceress Skill Levels', 30);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Arch-Angels', '+2 Sorceress Skill Levels', 50);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Shamans', '+1 Druid Skill Levels', 30);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Hierophants', '+2 Druid Skill Levels', 50);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Magekillers', '+1 Assassin Skill Levels', 30);
INSERT INTO MagicAffixTable VALUES('Prefix', '+All Skill Levels', 'Witch-hunters', '+2 Assassin Skill Levels', 50);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Amazon Skills', 'Fletchers', '+1 Amazon Bow and Crossbow Skills', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Amazon Skills', 'Bowyers', '+2 Amazon Bow and Crossbow Skills', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Amazon Skills', 'Archers', '+3 Amazon Bow and Crossbow Skills', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Amazon Skills', 'Acrobats', '+1 Amazon Passive Skills', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Amazon Skills', 'Gymnasts', '+2 Amazon Passive Skills', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Amazon Skills', 'Athletes', '+3 Amazon Passive Skills', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Amazon Skills', 'Harpoonists', '+1 Amazon Javelin and Spear Skills', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Amazon Skills', 'Spearmaidens', '+2 Amazon Javelin and Spear Skills', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Amazon Skills', 'Lancers', '+3 Amazon Javelin and Spear Skills', 60);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Sorceress Skills', 'Burning', '+1 Sorceress Fire Spells', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Sorceress Skills', 'Blazing', '+2 Sorceress Fire Spells', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Sorceress Skills', 'Volcanic', '+3 Sorceress Fire Spells', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Sorceress Skills', 'Sparking', '+1 Sorceress Lightning Spells', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Sorceress Skills', 'Charged', '+2 Sorceress Lightning Spells', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Sorceress Skills', 'Powered', '+3 Sorceress Lightning Spells', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Sorceress Skills', 'Chilling', '+1 Sorceress Cold Spells', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Sorceress Skills', 'Freezing', '+2 Sorceress Cold Spells', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Sorceress Skills', 'Glacial', '+3 Sorceress Cold Spells', 60);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Necromancer Skills', 'Hexing', '+1 Necromancer Curses', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Necromancer Skills', 'Blighting', '+2 Necromancer Curses', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Necromancer Skills', 'Accursed', '+3 Necromancer Curses', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Necromancer Skills', 'Fungal', '+1 Necromancer Poison and Bone Spells', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Necromancer Skills', 'Noxious', '+2 Necromancer Poison and Bone Spells', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Necromancer Skills', 'Venomous', '+3 Necromancer Poison and Bone Spells', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Necromancer Skills', 'Graverobbers', '+1 Necromancer Summoning Spells', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Necromancer Skills', 'Mojo', '+2 Necromancer Summoning Spells', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Necromancer Skills', 'Golemlords', '+3 Necromancer Summoning Spells', 60);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Paladin Skills', 'Lion Branded', '+1 Paladin Combat Skills', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Paladin Skills', 'Hawk Branded', '+2 Paladin Combat Skills', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Paladin Skills', 'Rose Branded', '+3 Paladin Combat Skills', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Paladin Skills', 'Captains', '+1 Paladin Offensive Auras', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Paladin Skills', 'Commanders', '+2 Paladin Offensive Auras', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Paladin Skills', 'Marshals', '+3 Paladin Offensive Auras', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Paladin Skills', 'Preservers', '+1 Paladin Defensive Auras', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Paladin Skills', 'Warders', '+2 Paladin Defensive Auras', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Paladin Skills', 'Guardians', '+3 Paladin Defensive Auras', 60);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Barbarian Skills', 'Experts', '+1 Barbarian Combat Skills', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Barbarian Skills', 'Veterans', '+2 Barbarian Combat Skills', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Barbarian Skills', 'Masters', '+3 Barbarian Combat Skills', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Barbarian Skills', 'Fanatic', '+1 Barbarian Combat Masteries', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Barbarian Skills', 'Raging', '+2 Barbarian Combat Masteries', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Barbarian Skills', 'Furious', '+3 Barbarian Combat Masteries', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Barbarian Skills', 'Sounding', '+1 Barbarian Warcries', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Barbarian Skills', 'Resonant', '+2 Barbarian Warcries', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Barbarian Skills', 'Echoing', '+3 Barbarian Warcries', 60);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Druid Skills', 'Trainers', '+1 Druid Summoning', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Druid Skills', 'Caretakers', '+2 Druid Summoning', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Druid Skills', 'Keepers', '+3 Druid Summoning', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Druid Skills', 'Spritual', '+1 Druid Shapeshifting', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Druid Skills', 'Feral', '+2 Druid Shapeshifting', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Druid Skills', 'Communal', '+3 Druid Shapeshifting', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Druid Skills', 'Natures', '+1 Druid Elemental', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Druid Skills', 'Terras', '+2 Druid Elemental', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Druid Skills', 'Gaeas', '+3 Druid Elemental', 60);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Assassin Skills', 'Entrapping', '+1 Assassin Traps', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Assassin Skills', 'Tricksters', '+2 Assassin Traps', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Assassin Skills', 'Cunning', '+3 Assassin Traps', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Assassin Skills', 'Mentalists', '+1 Assassin Shadow Disciplines', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Assassin Skills', 'Psychic', '+2 Assassin Shadow Disciplines', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Assassin Skills', 'Shadow', '+3 Assassin Shadow Disciplines', 60);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Assassin Skills', 'Shogukushas', '+1 Assassin Martial Arts', 20);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Assassin Skills', 'Senseis', '+2 Assassin Martial Arts', 40);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Assassin Skills', 'Kenshis', '+3 Assassin Martial Arts', 60);

INSERT INTO MagicAffixTable VALUES('Prefix', 'Damage Generates Mana', 'Vulpine', '7-12% Damage taken Goes to Mana', 9);

INSERT INTO MagicAffixTable VALUES('Prefix', 'Each Kill Generates Mana', 'Triumphant', '+1 Point of Mana After Each Kill', 3);
INSERT INTO MagicAffixTable VALUES('Prefix', 'Each Kill Generates Mana', 'Victorious', '+2-5 Point of Mana After Each Kill', 17);

INSERT INTO MagicAffixTable VALUES('Prefix', 'Better Chance of Getting Magic Items', 'Felicitous', '5-10% Better Chance of Getting Magic Item', 5);
INSERT INTO MagicAffixTable VALUES('Prefix', 'Better Chance of Getting Magic Items', 'Fortuitous', '11-15% Better Chance of Getting Magic Item', 12);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Max Stamina', 'Rugged', '+5-20 to Max Stamina', 1);
INSERT INTO MagicAffixTable VALUES('Prefix', '+Max Stamina', 'Vigorous', '+21-30 to Max Stamina', 16);

INSERT INTO MagicAffixTable VALUES('Prefix', '+Stamina Regeneration', 'Tireless', 'Heal Stamina +25-50%', 1);

INSERT INTO MagicAffixTable VALUES('Prefix', 'Make Monsters Flee When Hit', 'Screaming', 'Hit Causes Monsters to Flee 12-25% [16-32]', 10);
INSERT INTO MagicAffixTable VALUES('Prefix', 'Make Monsters Flee When Hit', 'Howling', 'Hit Causes Monsters to Flee 18-50% [24-64]', 16);
INSERT INTO MagicAffixTable VALUES('Prefix', 'Make Monsters Flee When Hit', 'Wailing', 'Hit Causes Monsters to Flee 25-100% [32-128]', 24);

INSERT INTO MagicAffixTable VALUES('Prefix', 'Add Sockets', 'Mechanics', 'Add 1-2 Sockets', 10);
INSERT INTO MagicAffixTable VALUES('Prefix', 'Add Sockets', 'Artisans', 'Add 3 Sockets', 33);
INSERT INTO MagicAffixTable VALUES('Prefix', 'Add Sockets', 'Jewelers', 'Add 4 Sockets', 55);

INSERT INTO MagicAffixTable VALUES('Prefix', 'Add Quantity To Throwing Weapons', 'Compact', '+20-40 Quantity', 2);
INSERT INTO MagicAffixTable VALUES('Prefix', 'Add Quantity To Throwing Weapons', 'Thin', '+41-80 Quantity', 17);
INSERT INTO MagicAffixTable VALUES('Prefix', 'Add Quantity To Throwing Weapons', 'Dense', '+80-120 Quantity', 38);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Strength', 'Strength', '+1-2 to Strength', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Strength', 'Might', '+3-5 to Strength', 10);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Strength', 'Ox', '+6-9 to Strength', 26);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Strength', 'Giant', '+10-15 to Strength', 42);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Strength', 'Titan', '+16-20 to Strength', 58);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Strength', 'Atlas', '+21-30 to Strength', 71);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Dexterity', 'Dexterity', '+1-2 to Dexterity', 2);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Dexterity', 'Skill', '+3-5 to Dexterity', 11);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Dexterity', 'Accuracy', '+6-9 to Dexterity', 27);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Dexterity', 'Precision', '+10-15 to Dexterity', 43);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Dexterity', 'Perfection', '+16-20 to Dexterity', 59);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Dexterity', 'Nirvana', '+21-30 to Dexterity', 72);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Energy', 'Energy', '+1-2 to Energy', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Energy', 'Mind', '+4-6 to Energy', 7);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Energy', 'Brilliance', '+7-10 to Energy', 13);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Energy', 'Sorcery', '+11-15 to Energy', 21);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Energy', 'Wizardry', '+16-20 to Energy', 31);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Energy', 'Enlightenment', '+21-30 to Energy', 41);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Life', 'Jackal', '+1-5 to Life', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life', 'Fox', '+6-10 to Life', 7);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life', 'Wolf', '+11-20 to Life', 11);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life', 'Tiger', '+21-30 to Life', 20);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life', 'Mammoth', '+31-40 to Life', 20);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life', 'Colossus', '+41-60 to Life', 30);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life', 'Squid', '+61-80 to Life', 40);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life', 'Whale', '+81-100 to Life', 50);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Light Radius', 'Light', '+1 to Light Radius, +15 To Attack Rating', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Light Radius', 'Radiance', '+3 to Light Radius, +30 To Attack Rating', 15);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Light Radius', 'Sun', '+5 to Light Radius, +5% To Attack Rating', 17);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Minimum Damage', 'Worth', '+1-2 to Minimum Damage', 2);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Minimum Damage', 'Measure', '+3-4 to Minimum Damage', 12);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Minimum Damage', 'Excellence', '+5-8 to Minimum Damage', 24);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Minimum Damage', 'Performance', '+9-14 to Minimum Damage', 48);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Minimum Damage', 'Transcendance', '+15-20 to Minimum Damage', 76);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Maximum Damage', 'Craftsmanship', '+1 to Maximum Damage', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Maximum Damage', 'Quality', '+2 to Maximum Damage', 4);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Maximum Damage', 'Maiming', '+3-4 to Maximum Damage', 7);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Maximum Damage', 'Slaying', '+5-7 to Maximum Damage', 11);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Maximum Damage', 'Gore', '+8-10 to Maximum Damage', 14);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Maximum Damage', 'Carnage', '+11-14 to Maximum Damage', 19);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Maximum Damage', 'Slaughter', '+15-20 to Maximum Damage', 25);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Maximum Damage', 'Butchery', '+21-40 to Maximum Damage', 35);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Maximum Damage', 'Evisceration', '+41-63 to Maximum Damage', 45);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Fire Damage', 'Flame', '+1 Minimum and 2-6 Maximum Fire Damage', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Fire Damage', 'Fire', '+1-4 Minimum and 6-11 Maximum Fire Damage', 15);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Fire Damage', 'Burning', '+5-9 Minimum and 10-20 Maximum Fire Damage', 25);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Fire Damage', 'Incineration', '+10-20 Minimum and 21-75 Maximum Fire Damage', 43);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Cold Damage', 'Frost', '+1 Minimum and 1-2 Maximum Cold Damage - 2 sec Duration', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Cold Damage', 'Icicle', '+1 Minimum and 3-4 Maximum Cold Damage - 3 sec Duration', 13);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Cold Damage', 'Glacier', '+2-4 Minimum and 4-15 Maximum Cold Damage - 4 sec Duration', 27);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Cold Damage', 'Winter', '+5-9 Minimum and 16-50 Maximum Cold Damage - 5 sec Duration', 45);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Lightning Damage', 'Shock', '+1 Minimum and 6-8 Maximum Lightning Damage', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Lightning Damage', 'Lightning', '+1 Minimum and 9-16 Maximum Lightning Damage', 15);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Lightning Damage', 'Thunder', '+1 Minimum and 17-40 Maximum Lightning Damage', 25);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Lightning Damage', 'Storms', '+1 Minimum and 40-120 Maximum Lightning Damage', 34);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Poison Damage', 'Blight', 'Adds 7 Poison Damage over 3 Seconds', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Poison Damage', 'Venom', 'Adds 21 Poison Damage over 4 Seconds', 15);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Poison Damage', 'Pestilence', 'Adds 50 Poison Damage over 5 Seconds', 25);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Poison Damage', 'Anthrax', 'Adds 100 Poison Damage over 6 Seconds', 33);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Poison Length Reduction', 'Remedy', 'Poison Length Reduced by 25%', 7);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Poison Length Reduction', 'Amelioration', 'Poison Length Reduced by 50%', 18);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Poison Length Reduction', 'Defiance', 'Poison Length Reduced by 75%', 18);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Life Stolen', 'Leech', '3-5% Life Stolen Per Hit', 6);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life Stolen', 'Locust', '5-7% Life Stolen Per Hit', 20);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life Stolen', 'Lamprey', '7-9% Life Stolen Per Hit', 55);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Mana Stolen', 'Bat', '3-5% Mana Stolen Per Hit', 7);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Mana Stolen', 'Wraith', '6-7% Mana Stolen Per Hit', 21);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Mana Stolen', 'Vampire', '7-9% Mana Stolen Per Hit', 56);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Life Regeneration', 'Regeneration', 'Replenish Life +3-5', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life Regeneration', 'Regrowth', 'Replenish Life +6-10', 17);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Life Regeneration', 'Revivification', 'Replenish Life +11-15', 38);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Weapon Speeds', 'Readiness', '10% Attack Speed Increase', 5);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Weapon Speeds', 'Alacrity', '20% Attack Speed Increase', 25);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Weapon Speeds', 'Swiftness', '30% Attack Speed Increase', 34);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Weapon Speeds', 'Quickness', '40% Attack Speed Increase', 46);

INSERT INTO MagicAffixTable VALUES('Suffix', '+Chance to Block', 'Blocking', '+10% Increased Blocking, 15% Faster Block Rate', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', '+Chance to Block', 'Deflecting', '+20% Increased Blocking, 30% Faster Block Rate', 11);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Faster Hit Recovery', 'Balance', '10% Faster Hit Recovery', 5);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Faster Hit Recovery', 'Equilibrium', '17% Faster Hit Recovery', 9);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Faster Hit Recovery', 'Stability', '24% Faster Hit Recovery', 18);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Damage Reduction', 'Health', 'Damage Reduced by 1', 7);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Damage Reduction', 'Protection', 'Damage Reduced by 2', 18);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Damage Reduction', 'Absorption', 'Damage Reduced by 3', 26);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Damage Reduction', 'Life', 'Damage Reduced by 4-7', 35);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Damage Reduction', 'Life Everlasting', 'Damage Reduced by 10-25', 45);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Damage Reduction', 'Anima', 'Damage Reduced by 8-15', 51);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Magic Damage Reduction', 'Warding', 'Magic Damage Reduced by 1', 7);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Magic Damage Reduction', 'Sentinel', 'Magic Damage Reduced by 2', 18);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Magic Damage Reduction', 'Guarding', 'Magic Damage Reduced by 3', 26);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Magic Damage Reduction', 'Negation', 'Magic Damage Reduced by 4-6', 41);

INSERT INTO MagicAffixTable VALUES('Suffix', 'More Gold', 'Greed', '25-40% Extra Gold From Monsters', 2);
INSERT INTO MagicAffixTable VALUES('Suffix', 'More Gold', 'Wealth', '41-80% Extra Gold From Monsters', 17);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Better Chance of Getting Magic Items', 'Chance', '5-15% Better Chance of Getting Magic Item', 2);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Better Chance of Getting Magic Items', 'Fortune', '16-25% Better Chance of Getting Magic Item', 16);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Better Chance of Getting Magic Items', 'Luck', '26-35% Better Chance of Getting Magic Item', 26);

INSERT INTO MagicAffixTable VALUES('Suffix', '-Cast Time', 'Apprentice', '10% Faster Cast Rate', 5);
INSERT INTO MagicAffixTable VALUES('Suffix', '-Cast Time', 'Magus', '20% Faster Cast Rate', 17);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Attacker Takes Damage', 'Thorns', 'Attacker Takes Damage of 1-3', 1);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Attacker Takes Damage', 'Spikes', 'Attacker Takes Damage of 4-6', 21);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Attacker Takes Damage', 'Razors', 'Attacker Takes Damage of 7-9', 34);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Attacker Takes Damage', 'Swords', 'Attacker Takes Damage of 10-20', 47);

INSERT INTO MagicAffixTable VALUES('Suffix', '-%Item Requirements', 'Ease', 'Requirements -20%', 15);
INSERT INTO MagicAffixTable VALUES('Suffix', '-%Item Requirements', 'Simplicity', 'Requirements -30%', 25);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Faster Walking/Running Speed', 'Pacing', '10% Faster Run/Walk', 2);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Faster Walking/Running Speed', 'Haste', '20% Faster Run/Walk', 22);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Faster Walking/Running Speed', 'Speed', '30% Faster Run/Walk', 37);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Faster Walking/Running Speed', 'Transportation', '30% Faster Run/Walk, Heal Stamina Plus 80-90%', 65);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Faster Walking/Running Speed', 'Acceleration', '40% Faster Run/Walk', 51);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Monster Knockback', 'Bear', 'Knockback', 8);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Attack Ignores Targets Defense', 'Piercing', 'Ignores Targets Defense', 25);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Prevent Monster Healing', 'Vileness', 'Prevent Monster Heal', 9);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Freeze Length Reduction', 'Warmth', 'Half Freeze Duration', 10);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Repair Durability', 'Self-Repair', 'Repair Durability (3)', 3);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Repair Durability', 'Fast-Repair', 'Repair Durability (5)', 20);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Indestructible', 'Ages', 'Indestructible', 50);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Replenish Quantity', 'Replenishing', 'Replenish Quantity (2)', 5);
INSERT INTO MagicAffixTable VALUES('Suffix', 'Replenish Quantity', 'Propogation', 'Replenish Quantity (24)', 24);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Life Per Level', 'Centaur', '+(0.75 Per Character Level)0.75-74.25 Life', 20);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Mana Per Level', 'Memory', '+(0.5 Per Character Level)0.5-49.5 To Mana', 20);

INSERT INTO MagicAffixTable VALUES('Suffix', 'Life and Mana Per Level', 'Elephant', '+(0.25 Per Character Level)0.25-24.75 To Life/+(0.25 Per Character Level)0.25-24.75 To Mana', 37);